name: DEV - Dispatch
on: 
  push:
    branches:    
      - develop
  workflow_dispatch:
jobs:
  unitest:
    name: UnitTest (XUnit)
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Unit Test (XUnit)
      run: |
        dotnet test --collect:"XPlat Code Coverage"
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"./XUnit.Tests/TestResults/*/coverage.cobertura.xml" -targetdir:"./coveragereport" -reporttypes:Html
    
    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: '${{ github.workspace }}/coveragereport/*'
        
  analyze:
    name: SAST CodeQL
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com/wuttipam/user15-tutorial-backend/security/code-scanning
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
       
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    # THIS IS INTERNAL ACITON ACCESS ONLY INTERNAL OGANIZAITON
    # - name: Quality Gate Check
    #   uses: <owner>/quality-gate-action@main
    #   with:
    #     repository: <owner>/xxx-xxxxxx
    #     severity: high
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
