name: SIT - Build
on:
  push:
    tags:
      - '*'
      env:
  ARTIFACT_NAME: "artifact-tutorial-backend"
  jobs:
...
  build:
    runs-on: ubuntu-latest
    environment:
      name: sit
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set env
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Pack Artifact
      run: cd Tutorial.Api/bin/Release/net6.0 && tar -zcvf ${{ env.ARTIFACT_NAME }}-${{ env.RELEASE_VERSION }}.tar.gz *
      
    - name: Upload Artifact Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/Tutorial.Api/bin/Release/net6.0/${{ env.ARTIFACT_NAME }}-${{ env.RELEASE_VERSION }}.tar.gz